const data=[
{name:'KBS 1라디오',badge:'KBS\n1라디오',freq:'97.3 MHz',cat:'뉴스 · 시사',type:'kbs',code:'21'},
{name:'KBS 2라디오',badge:'KBS\n2라디오',freq:'106.1 MHz',cat:'음악 · 생활정보',type:'kbs',code:'22'},
{name:'KBS 클래식FM',badge:'KBS\n클래식FM',freq:'93.1 MHz',cat:'클래식 · 음악',type:'kbs',code:'24'},
{name:'KBS 쿨FM',badge:'KBS\n쿨FM',freq:'89.1 MHz',cat:'음악 · 예능',type:'kbs',code:'25'},
{name:'SBS 파워FM',badge:'SBS\n파워FM',freq:'107.7 MHz',cat:'음악 · 예능',type:'sbs',schedule:'Power',streamApi:'https://apis.sbs.co.kr/play-api/1.0/livestream/powerpc/powerfm?protocol=hls&ssl=Y'},
{name:'SBS 러브FM',badge:'SBS\n러브FM',freq:'103.5 MHz',cat:'토크 · 음악',type:'sbs',schedule:'Love',streamApi:'https://apis.sbs.co.kr/play-api/1.0/livestream/lovepc/lovefm?protocol=hls&ssl=Y'}
];
const colors=['#1479e9','#2746b8','#7651db','#dc3165','#ef5b37','#e77a20'];
let idx=Math.min(+(localStorage.radioLast||0),data.length-1),playing=false,timer=0,timerHandle=null;
const $=x=>document.getElementById(x),audio=new Audio();audio.preload='none';audio.playsInline=true;
data.forEach((s,i)=>{const b=document.createElement('button');b.className='station';b.style.background=colors[i];b.innerHTML=`<strong>${s.badge.replace('\n','<br>')}</strong><small>${s.freq}</small><em>${s.cat}</em>`;b.onclick=()=>open(i);$('stations').appendChild(b)});
async function getKbs(s){const r=await fetch(`https://cfpwwwapi.kbs.co.kr/api/v1/landing/live/channel_code/${s.code}`);if(!r.ok)throw Error('KBS API');return r.json()}
async function getStream(s){if(s.type==='kbs'){const j=await getKbs(s);const item=(j.channel_item||j.channel?.item||[])[0];if(!item?.service_url)throw Error('KBS stream');return item.service_url}if(s.type==='sbs'){const r=await fetch(s.streamApi);const text=(await r.text()).trim();try{const j=JSON.parse(text);return j?.onair?.source?.mediasource?.mediaurl||j?.mediaurl||j?.url||text}catch{return text}}}
function hhmm(v){if(!v)return'';const d=String(v).replace(/\D/g,'');if(d.length>=4)return `${d.slice(-4,-2)}:${d.slice(-2)}`;const m=String(v).match(/(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:''}
function mins(v){const t=hhmm(v);if(!t)return null;const [h,m]=t.split(':').map(Number);return h*60+m}
function selectNow(items){items=items.filter(x=>x.title&&x.start).sort((a,b)=>mins(a.start)-mins(b.start));if(!items.length)return{};const d=new Date(),now=d.getHours()*60+d.getMinutes();let current=null,next=null;for(let i=0;i<items.length;i++){const a=mins(items[i].start),b=items[i].end?mins(items[i].end):(items[i+1]?mins(items[i+1].start):1440);if(a<=now&&now<(b<=a?b+1440:b)){current=items[i];next=items[i+1]||null;break}if(a>now&&!next)next=items[i]}return {current:current||items[items.length-1],next}}
function renderSchedule(current,next){if(!current)return false;$('program').textContent=current.title;$('programTime').textContent=current.end?`${hhmm(current.start)} ~ ${hhmm(current.end)}`:`${hhmm(current.start)}부터`;$('nextProgram').textContent=next?`다음 방송 · ${hhmm(next.start)} ${next.title}`:'';return true}
function today(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return {compact:`${y}${m}${day}`,sbs:`${y}/${d.getMonth()+1}/${d.getDate()}`}}
async function getKbsSchedule(s){const {compact}=today();const url=`https://static.api.kbs.co.kr/mediafactory/v1/schedule/weekly?local_station_code=00&channel_code=${s.code}&program_planned_date_from=${compact}&program_planned_date_to=${compact}`;const r=await fetch(url);if(!r.ok)throw Error('KBS schedule');const j=await r.json(),items=[];(Array.isArray(j)?j:[]).forEach(day=>{if(String(day.channel_code)!==String(s.code))return;(day.schedules||[]).forEach(x=>{const start=x.program_planned_start_time,end=x.program_planned_end_time,title=x.program_title;if(title&&start)items.push({title,start,end})})});return items}
async function getSbsSchedule(s){const {sbs}=today();const r=await fetch(`https://static.cloud.sbs.co.kr/schedule/${sbs}/${s.schedule}.json`);if(!r.ok)throw Error('SBS schedule');const j=await r.json(),rows=Array.isArray(j)?j:(j.schedulerPrograms||[]);return rows.map(x=>({title:x.title,start:x.start_time||x.starttime,end:x.end_time||x.endtime})).filter(x=>x.title&&x.start)}
async function loadProgram(s){$('program').textContent='편성 정보를 불러오는 중…';$('programTime').textContent='';$('nextProgram').textContent='';try{const items=s.type==='kbs'?await getKbsSchedule(s):await getSbsSchedule(s);const {current,next}=selectNow(items);if(renderSchedule(current,next))return;throw Error('empty schedule')}catch(e){console.error('schedule',e);$('program').textContent='현재 방송 중';$('programTime').textContent='편성 정보를 가져오지 못했어요'}}
async function playCurrent(){const btn=$('playBtn');try{btn.querySelector('span').textContent='연결 중';audio.src=await getStream(data[idx]);audio.volume=$('volume').value/100;await audio.play();setPlay(true)}catch(e){console.error(e);setPlay(false);btn.querySelector('span').textContent='다시 듣기';alert('이 방송은 지금 연결되지 않아요. 다른 방송을 선택해 주세요.')}}
function stopRadio(){audio.pause();audio.removeAttribute('src');audio.load();setPlay(false)}
function open(i){idx=(i+data.length)%data.length;localStorage.radioLast=idx;const s=data[idx];$('stationName').textContent=s.name;$('stationBadge').textContent=s.badge;$('stationBadge').style.background=colors[idx];$('frequency').textContent=s.freq;$('category').textContent=s.cat;$('home').classList.remove('active');$('player').classList.add('active');fav();loadProgram(s);playCurrent()}
function setPlay(v){playing=v;$('playBtn').childNodes[0].nodeValue=v?'■':'▶';$('playBtn').querySelector('span').textContent=v?'라디오 끄기':'다시 듣기'}
function fav(){const f=JSON.parse(localStorage.radioFav||'[]');$('favoriteBtn').childNodes[0].nodeValue=f.includes(idx)?'♥':'♡'}
$('backBtn').onclick=()=>{$('player').classList.remove('active');$('home').classList.add('active')};$('playBtn').onclick=()=>playing?stopRadio():playCurrent();$('prevBtn').onclick=()=>{stopRadio();open(idx-1)};$('nextBtn').onclick=()=>{stopRadio();open(idx+1)};$('resumeBtn').onclick=()=>open(Math.min(+(localStorage.radioLast||0),data.length-1));$('volume').oninput=e=>audio.volume=e.target.value/100;$('favoriteBtn').onclick=()=>{let f=JSON.parse(localStorage.radioFav||'[]');f=f.includes(idx)?f.filter(x=>x!==idx):[...f,idx];localStorage.radioFav=JSON.stringify(f);fav()};$('timerBtn').onclick=()=>{timer=timer===0?15:timer===15?30:timer===30?60:0;if(timerHandle)clearTimeout(timerHandle);if(timer)timerHandle=setTimeout(()=>{stopRadio();timer=0;$('timerBtn').textContent='🌙 수면 타이머: 꺼짐'},timer*60000);$('timerBtn').textContent=timer?`🌙 수면 타이머: ${timer}분`:'🌙 수면 타이머: 꺼짐'};audio.addEventListener('ended',()=>setPlay(false));